version: "3.8"

services:
  streamlit-app:
    platform: linux/amd64 # CPU命令セット統一のため追加
    build:
      context: .
      dockerfile: Dockerfile
    image: your-username/streamlit-app:latest  # 任意タグ
    container_name: streamlit-prod
    ports:
      - "80:8501"        # 外部80番 → コンテナ8501番
    restart: unless-stopped  # 落ちても自動再起動
    environment:
      # Streamlit 本番向け設定
      STREAMLIT_SERVER_HEADLESS: "true"
      STREAMLIT_SERVER_ENABLE_CORS: "false"
      STREAMLIT_SERVER_ADDRESS: "0.0.0.0"
      STREAMLIT_SERVER_PORT: "8501"